bookEx/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.views.generic.base import TemplateView
from bookMng.views import Register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/success', TemplateView.as_view(
        template_name="registration/register_success.html"), name='register-success'),
    path('register', Register.as_view(), name='register'),
    path('', include('django.contrib.auth.urls')),
    path('', include('bookMng.urls'))
]

bookMng/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('announcements', views.announcements, name='announcements'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('book_detail/<int:book_id>', views.book_detail, name='book_detail'),
    path('book_delete/<int:book_id>', views.book_delete, name='book_delete'),
    path('book_search', views.book_search, name='book_search'),
    path('cart', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout'),
    path('displaybooks', views.displaybooks, name='displaybooks'),
    path('mybooks', views.mybooks, name='mybooks'),
    path('postbook', views.postbook, name='postbook'),
    path('suprise_book', views.suprise_book, name='suprise_book'),
    path('wishlist', views.wishlist, name='wishlist')
]

bookMng/models.py
from django.db import models

from django.contrib.auth.models import User



class MainMenu(models.Model):
    item = models.CharField(max_length=200, unique=True)
    link = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.item


class Announcement(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=500)
    username = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    post_date = models.DateField(auto_now=True)

    def __str__(self):
        return str(self.title)


class Book(models.Model):
    name = models.CharField(max_length=200)
    web = models.URLField(max_length=200)
    price = models.DecimalField(decimal_places=2, max_digits=8)
    publishdate = models.DateField(auto_now=True)
    picture = models.FileField(upload_to='bookEx/static/uploads', blank=False)
    pic_path = models.CharField(max_length=300, editable=False, blank=True)
    username = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.name)


class BookSearch(models.Model):
    name = models.CharField(max_length=200, primary_key=True, default="")

    def __str__(self):
        return str(self.name)


class Cart(models.Model):
    seller_book_id = models.IntegerField()
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)


class Wish(models.Model):
    bookName = models.CharField("Book Name", max_length=200)
    theUser = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return str(self.bookName)


bookMng/forms.py
from django import forms
from django.forms import ModelForm

from .models import Announcement
from .models import Book
from .models import BookSearch
from .models import Cart
from .models import Wish


class AnnouncementForm(ModelForm):
    class Meta:
        model = Announcement
        fields = ['title', 'content']


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = [
            'name',
            'web',
            'price',
            'picture',
        ]


class CartForm(ModelForm):
    class Meta:
        model = Cart
        fields = ['seller_book_id']


class SearchForm(ModelForm):
    class Meta:
        model = BookSearch
        fields = ['name']


class WishForm(ModelForm):
    class Meta:
        model = Wish
        fields = ['bookName']

bookMng/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import MainMenu
from .models import Announcement
from .models import Book
from .models import Cart
from .models import Wish
from .forms import AnnouncementForm
from .forms import BookForm
from .forms import CartForm
from .forms import SearchForm
from .forms import WishForm

from random import randint


def index(request):
    num_of_announces = 3
    num_of_books = 4

    books_count = Book.objects.count()

    books = Book.objects.all()[(books_count - num_of_books):]
    for b in books:
        b.pic_path = b.picture.url[14:]

    return render(request,
                  'bookMng/index.html',
                  {
                      'title': "Home",
                      'header': "Welcome to Book Exchange System",
                      'item_list': MainMenu.objects.all(),
                      'announces': Announcement.objects.order_by('-id')[:num_of_announces],
                      'cart_size': Cart.objects.filter(user=request.user.id).count(),
                      'books': books
                  })


def aboutus(request):
    return render(request,
                  'bookMng/aboutus.html',
                  {
                      'title': "About Us",
                      'item_list': MainMenu.objects.all(),
                      'cart_size': Cart.objects.filter(user=request.user.id).count()
                  })


def announcements(request):
    if request.method == 'POST':
        form = AnnouncementForm(request.POST)
        if form.is_valid():
            a = form.save(commit=False)
            a.username = request.user
            a.save()
            return HttpResponseRedirect('/announcements')
    else:
        form = AnnouncementForm()

    return render(request,
                  'bookMng/announcements.html',
                  {
                      'title': "Announcements",
                      'form': form,
                      'item_list': MainMenu.objects.all(),
                      'announces': Announcement.objects.order_by('-id'),
                      'cart_size': Cart.objects.filter(user=request.user.id).count()
                  })


@login_required(login_url=reverse_lazy('login'))
def book_delete(request, book_id):
    book = Book.objects.get(id=book_id)
    book.delete()
    return render(request,
                  'bookMng/book_delete.html',
                  {
                      'title': "Book Delete",
                      'item_list': MainMenu.objects.all(),
                      'book': book,
                      'cart_size': Cart.objects.filter(user=request.user.id).count()
                  })


@login_required(login_url=reverse_lazy('login'))
def book_detail(request, book_id):
    uid = request.user.id
    book = Book.objects.get(id=book_id)
    book_ids = [book_ids for book_ids, in Cart.objects.filter(user=uid).values_list('seller_book_id')]

    if request.method == 'POST':
        form = CartForm(request.POST)
        if form.is_valid():
            a = form.save(commit=False)
            a.user = request.user
            a.seller_book_id = book_id
            a.save()
            return HttpResponseRedirect('/cart')
    else:
        form = CartForm()
    
    book.pic_path = book.picture.url[14:]
    return render(request,
                  'bookMng/book_detail.html',
                  {
                      'title': "Book Details",
                      'form': form,
                      'item_list': MainMenu.objects.all(),
                      'book': book,
                      'cart_size': Cart.objects.filter(user=uid).count(),
                      'cart_items': list(Cart.objects.filter(user=uid).values_list('seller_book_id')),
                      'book_ids': book_ids
                  })


@login_required(login_url=reverse_lazy('login'))
def book_search(request, searched=""):

    submitted = False
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            a = form.save(commit=False)
            a.name = request.POST.get('name')
            return HttpResponseRedirect('/book_search?q=' + a.name)
    else:
        form = SearchForm()
        if 'q' in request.GET:
            searched = request.GET.get('q', '')
            submitted = True

    books = Book.objects.filter(name__icontains=searched)
    for b in books:
        b.pic_path = b.picture.url[14:]

    return render(request, 'bookMng/book_search.html',
                  {
                      'title': "Book Search",
                      'item_list': MainMenu.objects.all(),
                      'books': books,
                      'submitted': submitted,
                      'form': form,
                      'searched': searched,
                      'cart_size': Cart.objects.filter(user=request.user.id).count()
                  })


@login_required(login_url=reverse_lazy('login'))
def cart(request):
    uid = request.user.id

    if request.method == 'POST':
        item_to_remove = Cart.objects.filter(user=uid).get(seller_book_id=request.POST.get('to_remove'))
        item_to_remove.delete()
        return HttpResponseRedirect('/cart')

    the_cart = [book_ids for book_ids, in Cart.objects.filter(user=uid).values_list('seller_book_id')]
    total_price = 0

    books = []
    for cart_id in the_cart:
        book = Book.objects.get(id=cart_id)
        total_price += book.price
        books.append(book)

    for b in books:
        b.pic_path = b.picture.url[14:]

    return render(request,
                  'bookMng/cart.html',
                  {
                      'title': "Cart",
                      'item_list': MainMenu.objects.all(),
                      'books': books,
                      'cart_size': Cart.objects.filter(user=uid).count(),
                      'total_price': total_price
                  })


@login_required(login_url=reverse_lazy('login'))
def checkout(request):
    uid = request.user.id
    cart_book_ids = [book_ids for book_ids, in Cart.objects.filter(user=uid).values_list('seller_book_id')]

    if request.method == 'POST':
        for cart_id in cart_book_ids:
            book = Book.objects.get(id=cart_id)
            book.username_id = uid
            book.save()
            Cart.objects.filter(seller_book_id=cart_id).delete()

        return HttpResponseRedirect('/checkout')

    total_price = 0

    books = []
    for cart_id in cart_book_ids:
        book = Book.objects.get(id=cart_id)
        total_price += book.price
        books.append(book)

    for b in books:
        b.pic_path = b.picture.url[14:]

    return render(request,
                  'bookMng/checkout.html',
                  {
                      'title': "Checkout",
                      'item_list': MainMenu.objects.all(),
                      'books': books,
                      'cart_size': Cart.objects.filter(user=uid).count(),
                      'total_price': total_price
                  })


@login_required(login_url=reverse_lazy('login'))
def displaybooks(request):
    books = Book.objects.all()
    for b in books:
        b.pic_path = b.picture.url[14:]

    return render(request,
                  'bookMng/displaybooks.html',
                  {
                      'title': "Display Books",
                      'item_list': MainMenu.objects.all(),
                      'books': books,
                      'cart_size': Cart.objects.filter(user=request.user.id).count()
                  })


@login_required(login_url=reverse_lazy('login'))
def mybooks(request):
    books = Book.objects.filter(username=request.user)
    for b in books:
        b.pic_path = b.picture.url[14:]
    return render(request,
                  'bookMng/mybooks.html',
                  {
                      'title': "My Books",
                      'item_list': MainMenu.objects.all(),
                      'books': books,
                      'cart_size': Cart.objects.filter(user=request.user.id).count()
                  })


@login_required(login_url=reverse_lazy('login'))
def postbook(request):
    submitted = False
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save(commit=False)
            try:
                book.username = request.user
            except Exception:
                pass
            book.save()
            return HttpResponseRedirect('/postbook?submitted=True')
    else:
        form = BookForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request,
                  'bookMng/postbook.html',
                  {
                      'title': "Post Book",
                      'form': form,
                      'item_list': MainMenu.objects.all(),
                      'submitted': submitted,
                      'cart_size': Cart.objects.filter(user=request.user.id).count()
                  })


@login_required(login_url=reverse_lazy('login'))
def suprise_book(request):

    num_of_books = Book.objects.count()
    ran = randint(1, num_of_books) - 1

    book = Book.objects.all()[ran]
    book.pic_path = book.picture.url[14:]

    return render(request, 'bookMng/suprise_book.html',
                  {
                      'title': "Surprise Book",
                      'item_list': MainMenu.objects.all(),
                      'book': book,

bookEx/templates/bookMng/aboutus.html
{% extends "base.html" %}
{% load static %}



{% block header %}

    <div class="d-flex flex-row align-items-center align-self-center">
        <div class="d-flex flex-row mb-0">
            About Us - Group 4
        </div>
    </div>

{% endblock header %}


{% block body %}

    <div class="d-inline-flex flex-column">
        <div class="f-flex flex-column pb-2">
            <div class="h5">School</div>
            <div class="ps-3 pb-1">Cal State Los Angeles - Computer Science Department</div>
        </div>

        <div class="f-flex flex-column py-2">
            <div class="h5">Professor</div>
            <div class="ps-3 pb-1">Jiang Guo</div>
        </div>

        <div class="d-flex flex-column py-2">
            <div class="h5">Students/Developers</div>
            <div class="ps-3">
                <div class="py-1">Julaton, Jimuel</div>
                <div class="py-1">Lin, Chen-Ching</div>
                <div class="py-1">Liu, Saiyang</div>
                <div class="py-1">Lum, Jeffrey</div>
                <div class="py-1">Mai, Simon</div>
                <div class="py-1">Manese, Ashley</div>
                <div class="py-1">Moreno, Cristian</div>
            </div>
        </div>

    </div>
    
{% endblock body %}

bookEx/templates/bookMng/announcements.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}




{% block header %}

    <div class="d-flex flex-row align-items-center align-self-center">
        <div class="d-flex flex-row mb-0">
            Announcements
            {% if user.is_superuser %}
            <div class="ms-2 text-primary" href="#new" data-bs-toggle="collapse" role="button" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="new announcements">
                <i class="bi bi-plus-square"></i>
            </div>
            {% endif %}
        </div>
    </div>

{% endblock header %}



{% block body %}

    {% if user.is_superuser %}
    <div id="new" class="multi-collapse collapse">

        <form enctype="multipart/form-data" method="post" novalidate>
            <div class="form-group d-flex flex-column multi-collapse collapse" id="new">
                <div class="py-2 d-inline-flex">
                    <div style="width:14rem;">
                        <label for="title" class="form-label">Title</label>
                        {{ form.title|add_class:"form-control"|attr:"id:title"|attr:"placeholder:Title" }}
                    </div>
                </div>
                <div class="py-2 d-flex flex-wrap">
                    <div style="width:33rem;">
                        <label for="content_area" class="form-label">Content</label>
                        {{ form.content|add_class:"form-control"|attr:"id:content_area"|attr:"placeholder:Enter content"|attr:"rows:4" }}
                    </div>
                </div>
                <div class="py-2 d-flex flex-row">
                    <button class="d-inline-flex btn btn-primary me-1" type="submit">Submit</button>
                    <div class="d-inline-flex btn btn-secondary ms-1" href="#new" data-bs-toggle="collapse" role="button" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="new announcements">Cancel</div>
                </div>
            </div>
            {% csrf_token %}
        </form>
        
    </div>
    {% endif %}


    <div id="announcements" class="multi-collapse collape show">
        {% for a in announces %}
        <div class="accordion rounded py-2" id="accordion{{ a.id }}">
            <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{ a.id }}">
                    <div class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ a.id }}" aria-expanded="false" aria-controls="collapse{{ a.id }}">
                        <div class="pe-2 text-muted">
                            {{ a.post_date }} -
                        </div>
                        {{ a.title }}
                    </div>
                </h2>
                <div id="collapse{{ a.id }}" class=" collapse" aria-labelledby="heading{{ a.id }}" data-bs-parent="#accordion{{ a.id }}">
                    <div class="accordion-body">
                        <div class="d-flex flex-column">
                            <div>{{ a.content|linebreaksbr }}</div>
                            <div class="text-muted mt-2">[ {{ a.username }} ]</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock body %}

bookEx/templates/bookMng/book_delete.html
{% extends "base.html" %}
{% load static %}



{% block body %}

    <p>Delete Successfully!</p>

{% endblock body %}

bookEx/templates/bookMng/book_detail.html
{% extends "base.html" %}
{% load static %}



{% block body %}

    <div class="d-flex">
        <div class="d-flex flex-column flex-md-row m-2 shadow rounded p-2 align-items-center bg-light">
            <div class="d-flex p-2 mx-auto mx-md-0 bg-light">
                    <img src="
                        {% if book.picture %}
                            {% static book.pic_path %}
                        {% else %}
                            {% static 'logo.jpg' %}
                        {% endif %}
                    " style="max-width: 150px; max-height: 100%;" />
            </div>
            <div class="d-flex flex-row flex-wrap p-2 bg-light">
                    <table class="table-borderless d-inline-flex text-start">
                        <tr>
                            <th class="p-2 text-end">Title: </td>
                            <td class="p-2">{{ book.name }}</td>
                        </tr>
                        <tr>
                            <th class="p-2 text-end">Web: </td>
                            <td class="p-2">{{ book.web }}</td>
                        </tr>
                        <tr>
                            <th class="p-2 text-end ">Price: </td>
                            <td class="p-2">${{ book.price }}</td>
                        </tr>
                        <tr>
                            <th class="p-2 text-end">Published: </td>
                            <td class="p-2">{{ book.publishdate }}</td>
                        </tr>
                        <tr>
                            <th class="p-2 text-end">Owner: </td>
                            <td class="p-2">{{ book.username }}</td>
                        </tr>
                    </table>
            </div>
        </div>
    </div>

{% endblock body %}

bookEx/templates/bookMng/book_search.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}



{% block body %}

    <form enctype="multipart/form-data" method="post" novalidate>
        <div class="form-group d-flex flex-row justify-content-start align-items-center pb-2">
            <div class="text-nowrap">
                <label for="id_name" class="form-label">Book Search</label>
            </div>
            <div class="px-2">
                {% render_field form.name class="form-control" value=searched autofocus=autofocus %}
            </div>
            <div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
        {% csrf_token %}
    </form>
    {% if submitted %}
    <h5>Results for "{{ searched }}"</h5>

    <div class="d-flex flex-row flex-wrap justify-content-evenly justify-content-lg-start">
        {% for book in books %}
            <div class="d-flex flex-column m-2 rounded bg-light shadow-sm" style="width: 10rem;">

                <div class="card-header text-center text-truncate border-0 bg-light">
                    <a href="book_detail/{{ book.id }}" class="text-decoration-none">{{ book.name }}</a>
                </div>

                <div class="mx-auto my-0 d-flex bg-light" style="width: 80%;">
                    <a href="book_detail/{{ book.id }}" class="mx-auto">
                        <img src="
                            {% if book.picture %}
                                {% static book.pic_path %}
                            {% else %}
                                {% static 'logo.jpg' %}
                            {% endif %}
                        " style="max-width: 100%; max-height: 100%;"height="175" />
                    </a>
                </div>

                <div class="card-footer p-2 border-0 text-muted bg-light">
                    <div class="mt-auto user-select-none">Owner: {{ book.username }}</div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% endif %}

{% endblock body %}

bookEx/templates/bookMng/cart.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}


{% block body %}

    <div class="d-flex flex-column align-items-center">
        <div class="py-1 d-inline-flex">Subtotal ({{ cart_size }} items): <div class="ps-2 fw-bold"> ${{ total_price }}</div></div>
        <div class="py-1 d-flex">
            <a href="{% url 'checkout' %}" class="btn btn-warning {% if cart_size == 0 %}disabled{% endif %}" type="submit">Go to checkout</a>
        </div>
    </div>
    <hr>
    {% for book in books %}
    <div class="py-2 d-flex flex-column flex-md-row rounded align-items-start">
        <div class="d-flex flex-column p-0 mx-auto mx-md-0 bg-transparent">
            <img src="
                {% if book.picture %}
                    {% static book.pic_path %}
                {% else %}
                    {% static 'logo.jpg' %}
                {% endif %}
            " height="175"/>
            <div class="mx-auto pt-2">
                <form enctype="multipart/form-data" method="post" novalidate>
                    <input type="hidden" value="{{ book.id }}" name="to_remove">
                    <button class="btn btn-warning" type="submit">Remove</button>
                    {% csrf_token %}
                </form>
            </div>
        </div>

        <div class="ps-0 pt-2 ps-md-2 d-flex flex-column flex-wrap bg-transparent">
            <table class="table-borderless d-flex flex-column">
                <tr>
                    <th class="pb-2 text-end">Title: </th>
                    <td class="pb-2 ps-2">{{ book.name }}</td>
                </tr>
                <tr>
                    <th class="text-end">Web: </th>
                    <td class="py-2 ps-2"><a href="{{ book.web }}" class="text-decoration-none" target="_blank">{{ book.web|truncatechars:45 }} <i class="bi bi-box-arrow-up-right"></i></a></td>
                </tr>
                <tr>
                    <th class="text-end">Price: </th>
                    <td class="py-2 ps-2">${{ book.price }}</td>
                </tr>
                <tr>
                    <th class="text-end">Published: </th>
                    <td class="py-2 ps-2">{{ book.publishdate }}</td>
                </tr>
                <tr>
                    <th class="pt-2 text-end">User: </th>
                    <td class="pt-2 ps-2">{{ book.username }}</td>
                </tr>
            </table>
        </div>
    </div>
    <hr>
    {% endfor %}

{% endblock body %}

bookEx/templates/bookMng/displaybooks.html
{% extends "base.html" %}
{% load static %}


{% block body %}

    <div class="d-flex flex-row flex-wrap justify-content-evenly justify-content-lg-start">
        {% for book in books %}
            <div class="d-flex flex-column m-2 rounded bg-light shadow-sm hover-shadow" data-trigger="hover focus" style="width: 10rem;" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-original-title="{{ book.name }}">

                <div class="card-header text-center text-truncate border-0 bg-light">
                    <a href="book_detail/{{ book.id }}" class="text-decoration-none">
                        {{ book.name }}
                    </a>
                </div>

                <div class="mx-auto m-0 bg-light">
                    <a href="book_detail/{{ book.id }}">
                        <img src="
                            {% if book.picture %}
                                {% static book.pic_path %}
                            {% else %}
                                {% static 'logo.jpg' %}
                            {% endif %}
                        " height="175" />
                    </a>
                </div>

                <div class="card-footer p-2 border-0 text-muted bg-light">
                    <div class="mt-auto user-select-none">User: {{ book.username }}</div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock body %}

bookEx/templates/bookMng/postbook.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}



{% block body %}

    {% if submitted %}
        <p>Post successful! Post another <a href="{% url 'postbook' %}">one</a>!</p>
    {% else %}
        <div class="container-fluid mx-md-0" style="max-width: 450px;">
            <div class="row justify-content-start row-cols-1">
                <form enctype="multipart/form-data" method="post" novalidate>
                    <div class="col pb-2">
                        <div class="row g-0 align-items-md-center">
                            <div class="pb-1 col-auto text-start"><label for="id_name">Name</label></div>
                            <div class="col-12">{{ form.name|add_class:"form-control"|attr:"autofocus" }}</div>
                        </div>
                    </div>
                    <div class="col pb-2">
                        <div class="row g-0 align-items-md-center">
                            <div class="pb-1 col-auto text-start"><label for="id_web">Web</label></div>
                            <div class="col-12">{{ form.web|add_class:"form-control" }}</div>
                        </div>
                    </div>
                    <div class="col pb-2">
                        <div class="row g-0 align-items-md-center">
                            <div class="pb-1 col-auto text-start"><label for="id_price">Price</label></div>
                            <div class="col-12">{{ form.price|add_class:"form-control" }}</div>
                        </div>
                    </div>
                    <div class="col pb-2">
                        <div class="row g-0 align-items-md-center">
                            <div class="pb-1 col-auto text-start"><label for="id_picture">Picture</label></div>
                            <div class="col-12">{{ form.picture|add_class:"form-control" }}</div>
                        </div>
                    </div>
                    <div class="col pb-2">
                        <div class="row g-0 align-items-md-center">
                            <div class="col-auto text-start"">
                                <button type="submit" class="btn btn-primary" role="button">Submit</button>
                                {% csrf_token %}
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    {% endif %}



{% endblock body %}

bookEx/templates/bookMng/wishlist.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}



{% block header %}

    <div class="d-flex flex-row align-items-center align-self-center">
        <div class="d-flex flex-row mb-0">
            Wishlist
            <div class="ms-2 text-primary" href="#addWish" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="addWish">
                <i class="bi bi-plus-square"></i>
            </div>
        </div>
    </div>

{% endblock header %}


{% block body %}

    {% if user.is_authenticated  %}
    <div id="addWish" class="multi-collapse collapse">

        <form enctype="multipart/form-data" method="post" novalidate>
            <div class="form-group d-flex flex-row justify-content-start align-items-center pb-2">
                <div class="text-nowrap">
                    <label for="id_bookName" class="form-label">Book Name</label>
                </div>
                <div class="px-2">
                        {{ form.bookName|add_class:"form-control"|attr:"autofocus" }}
                </div>
                <div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
            {% csrf_token %}
        </form>
    </div>
    {% endif %}

        <div class="d-flex flex-row flex-wrap justify-content-around justify-content-md-start align-items-stretch">
            <table class="d-inline-flex">
                <tr class="border-dark border-bottom">
                    <th class="p-2">Book Name</th>
                    <th class="p-2">Wished by</th>
                </tr>
                {% for wish in wish_list %}
                    <tr class="border-bottom">
                        <td class="p-2">{{ wish.bookName }}</td>
                        <td class="p-2">{{ wish.theUser.username }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>

{% endblock body %}